### PR TITLE
remove imports of start, next and done from Base

### PR DESCRIPTION
**Pull request by mkborregaard**
and replace with import of iterate.
Finalizes the update to the new iterator protocol.

### CODE REVIEW

**Comment by stevengj** [comment]
I would rather not import iterate. Nowadays I think the preferred style is to explicitly qualify functions that you are adding methods to rather than importing.

**Comment by mkborregaard** [comment]
Sure thing, I just aimed for consistency with the existing code. I've removed the import. There are still 3 test errors when I test PyCall locally on 1.0, but they seem unrelated to this.

**Comment by Datseris** [comment]
Also added in #522 which fixes "all" of 1.0 issues.

**Comment by mkborregaard** [comment]
Alright, I'll close this then.

**Pull request closed without merging**
