### PR TITLE
Make sure that test is run with Numpy in CI

### PR DESCRIPTION
**Pull request by tkf**
I noticed that #825 was not enough since it does not run the tests with Numpy on GitHub actions. This PR fixes it and also makes sure that we run the test with Numpy on any CI.

### CODE REVIEW

**Comment by stevengj** [comment]
Conflicts now that travis and appveyor files were deleted.

**Comment by tkf** [comment]
I fixed the merge conflict.

It looks like AppVeyor is complaining because it tries to run some test with the default setting. Can you turn off AppVeyor setting? https://ci.appveyor.com/project/StevenGJohnson/pycall-jl-nu3aa

**Comment by stevengj** [comment]
I just turned off AppVeyor and Travis for PyCall.jl

**Comment by tkf** [comment]
Thanks!  I'll merge this once the tests pass.

**Pull request merged**
