### PR TITLE
avoid jl_value_ptr

### PR DESCRIPTION
**Pull request by stevengj**
A cleaner solution to JuliaLang/julia#31473 and #670.

### CODE REVIEW

**Comment by yuyichao** [comment]
Technically this is dangerous since the argument to `unsafe_convert` is not guaranteed rooted by the caller here. The current implementation my or may not take advantage of this but it is technically allowed to assume that and give wrong result.. `pointer_from_objref` should be fine.

**Comment by stevengj** [comment]
@yuyichao, the `jlWrapType` variable is a `const` precisely because we can't allow it to be garbage-collected as long as we are using the `tp_base` pointer.

So, for the same reason, I don't think rooting is an issue?

**Comment by stevengj** [comment]
I guess in theory the `RefValue` object needs to be rooted too, so I would need a `GC.@preserve` here.

**Comment by yuyichao** [comment]
Correct, it's the

>  argument to `unsafe_convert`

that's the issue.

**Pull request merged**
