### PR TITLE
various fixes to array conversions

### PR DESCRIPTION
**Pull request by stevengj**
Add bounds-checking, GC rooting, and `CartesianIndex` support in `PyArray`. Fixes conversion for arrays of pointers/pyptrs and 0-dimensional arrays.

Fixes JuliaPy/PyPlot.jl#431

### CODE REVIEW

**Comment by stevengj** [comment]
So far I'm not able to reproduce the Travis failure on nightly locally.  @tkf, does it work for you?

**Comment by tkf** [comment]
I checked this branch with 1.2.0-DEV.339 at-colon/00f257d603 and 1.2.0-DEV.521 b076d04bf4. I couldn't reproduce the failure in Travis.

**Comment by stevengj** [comment]
I tried restarting Travis and the problem seems to have gone away!  So maybe it was a temporary bug that I was triggering in nightly that got fixed.

Now I'm seeing an unrelated failure:
```
The following packages have unmet dependencies:
 python3.4-venv : Depends: python-setuptools-whl but it is not installable
                  Depends: python-pip-whl but it is not installable
E: Unable to correct problems, you have held broken packages.
```
I will restart Travis again in case this is a temporary Travis hiccup, since I wasn't seeing this yesterday.

**Comment by stevengj** [comment]
Yay, it's green now!

**Pull request merged**
